<x-app-layout>
<x-slot name="header"><h1 class="font-semibold text-xl text-white">Prenotazioni e pagamenti AMD Rent</h1></x-slot>
@php $money = fn ($cents) => number_format($cents / 100, 2, ',', '.').' €'; @endphp
<div class="amr"><x-amd-rent-nav />@include('amd-rent.feedback')
<section class="amr-panel app-surface"><h2>Dal pagamento online al ritiro</h2><p>Le nuove prenotazioni prevedono una quota online incassata da AMD Rent. Verifica lo stato del pagamento prima di preparare la consegna. Le prenotazioni precedenti conservano le condizioni accettate.</p>
<form class="amr-filter" method="get"><div><label for="booking-search">Riferimento, cognome o email</label><input class="app-field" id="booking-search" name="q" maxlength="100" value="{{ $filters['q'] ?? '' }}"></div><div><label for="payment-filter">Pagamento</label><select class="app-field" id="payment-filter" name="payment"><option value="">Tutti</option>@foreach(['pending' => 'In attesa', 'paid' => 'Quota online pagata', 'review' => 'Da verificare', 'expired' => 'Scaduto', 'failed' => 'Non avviato', 'refunded' => 'Annullata e rimborsata', 'pickup' => 'Interamente al ritiro (precedenti)'] as $key => $label)<option value="{{ $key }}" @selected(($filters['payment'] ?? '') === $key)>{{ $label }}</option>@endforeach</select></div><button class="amr-button">Cerca</button><a class="amr-link" href="{{ route('public-bookings.index') }}">Azzera</a></form></section>
@forelse($bookings as $booking)<article class="amr-panel app-surface"><div class="amr-row-title"><h2>{{ $booking->first_name }} {{ $booking->last_name }}</h2><strong>{{ $booking->status_label }}</strong></div><p class="app-muted">{{ $booking->reference }} · {{ $booking->quote_snapshot['organization'] }}</p>
<div class="amr-columns"><div><h3>Auto e appuntamento</h3><p>{{ $booking->quote_snapshot['title'] }}<br>{{ $booking->pickup_at->format('d/m/Y H:i') }} – {{ $booking->return_at->format('d/m/Y H:i') }}</p><p>{{ $booking->quote_snapshot['location'] }} — {{ $booking->quote_snapshot['city'] }}</p>
@if(!empty($booking->quote_snapshot['delivery_address']))<p>Consegna concordata: <strong>{{ $booking->quote_snapshot['delivery_address'] }}</strong></p>@endif
@if(!empty($booking->quote_snapshot['return_address']))<p>Riconsegna concordata: <strong>{{ $booking->quote_snapshot['return_address'] }}</strong></p>@endif
@include('public-cars.partials.selected-map-point', ['point' => $booking->quote_snapshot['return_destination'] ?? null, 'pointType' => 'return'])
<p>{{ $booking->email }}<br>{{ $booking->phone }}</p></div>
<div><h3>Importi concordati</h3><p>Totale: <strong>{{ $money($booking->total_cents) }}</strong>@if($booking->delivery_fee_cents)<br>{{ !empty($booking->quote_snapshot['return_address']) ? 'Di cui ritiro e riconsegna' : 'Di cui consegna' }}: {{ $money($booking->delivery_fee_cents) }}@endif</p>
@if($booking->payment_method === 'stripe')<p>Versato online ad AMD Rent: <strong>{{ $money($booking->online_paid_cents - $booking->refunded_cents) }}</strong><br>Saldo previsto al ritiro: <strong>{{ $money($booking->pickup_due_cents) }}</strong></p><p>La quota online copre la commissione AMD Rent. Non richiederla nuovamente al cliente.</p>@if($booking->refunded_cents)<p>Rimborsato da Stripe: {{ $money($booking->refunded_cents) }}. Verificare gli importi residui e la prenotazione con AMD Rent.</p>@endif
@else<p>Pagamento concordato interamente al ritiro.</p>@endif<p>Cauzione separata: {{ $money($booking->deposit_cents) }}</p></div></div>
<div class="amr-actions">@if($booking->rental && !$booking->rental->trashed())@can('view', $booking->rental)<a class="amr-button" href="{{ route('rentals.show', $booking->rental_id) }}">Apri noleggio n. {{ $booking->rental->display_number }}</a>@endcan @endif<a class="amr-link" href="{{ $booking->confirmationUrl() }}" target="_blank" rel="noopener noreferrer">Riepilogo cliente</a><a class="amr-link" href="{{ $booking->pdfUrl(true) }}">Scarica PDF</a></div>
@if($booking->payment_status === 'pending')<p class="app-muted">L’auto è temporaneamente riservata; il pagamento non è ancora confermato. La scadenza viene riconciliata con Stripe prima di liberare l’auto.</p>@endif
@if($booking->payment_status === 'review')<p class="amr-notice">Pagamento da verificare con AMD Rent: la prenotazione non va modificata prima della riconciliazione.</p>@include('amd-rent.payment-review')@endif
<details class="amr-disclosure"><summary>Condividi il riepilogo</summary><div class="amr-actions"><a class="amr-link" href="{{ $booking->emailComposeUrl() }}">Prepara email</a>@if($booking->whatsappComposeUrl())<a class="amr-link" href="{{ $booking->whatsappComposeUrl() }}" target="_blank" rel="noopener noreferrer">Prepara WhatsApp</a>@endif<a class="amr-link" href="{{ $booking->pdfUrl() }}" target="_blank" rel="noopener noreferrer">Stampa riepilogo</a></div><p>Controlla il messaggio prima di inviarlo. Il PDF va allegato manualmente.</p></details>
</article>@empty<section class="amr-panel app-surface"><p>Nessuna prenotazione corrisponde alla selezione.</p></section>@endforelse{{ $bookings->links() }}</div></x-app-layout>
