@extends('layouts.public-cars')
@section('title', 'Noleggio a lungo termine')
@section('main-class', 'amd-info-page')
@section('content')
<div class="amd-info-heading"><div class="amd-section-inner amd-photo-heading">
    <div><h1>Un’auto per i tuoi prossimi progetti.</h1><p>Ogni giorno, per lavoro o per te. Raccontaci che auto cerchi e ricevi una proposta di noleggio a lungo termine da valutare con calma.</p></div>
    @include('public-cars.partials.context-photo', ['photoScene' => 'long-term'])
</div></div>
<div class="amd-section-inner amd-long-term-layout"><aside class="amd-information"><h2>Prima una proposta,<br>poi la tua scelta.</h2><p>Indica l’auto desiderata, la durata e i chilometri previsti. La richiesta può riguardare un privato, un professionista o un’azienda.</p><h3>Cosa succede alla richiesta</h3><p>AMD Rent la prende in carico e può affidarla a un noleggiatore. I preventivi riportano società fornitrice, canone, anticipo, durata, chilometri e condizioni.</p><h3>Il contratto si conclude di persona</h3><p>L’invio del modulo non prenota un veicolo e non richiede un pagamento online. La proposta e i documenti vengono verificati prima della firma in presenza.</p><p>Disponibilità, servizi e importi saranno indicati nel preventivo: non sono garantiti dalla sola richiesta.</p></aside>
<form class="amd-detail-info amd-booking-form amd-long-term-form" method="post" action="{{ route('public-site.long-term.store') }}">@csrf<input type="hidden" name="request_token" value="{{ $token }}"><h2>Richiedi un preventivo</h2>@if($errors->any())<div class="amd-errors" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@include('amd-rent.enquiries.fields')<div class="amd-booking-trap" aria-hidden="true"><label for="long-term-website">Sito web</label><input id="long-term-website" name="website" tabindex="-1" autocomplete="off"></div><label class="amd-booking-accept"><input type="checkbox" name="accept_contact" value="1" required><span>Chiedo di essere ricontattato per questa richiesta.@if(config('public_cars.privacy_url')) Ho letto l’<a href="{{ config('public_cars.privacy_url') }}">informativa privacy</a>.@endif</span></label><button class="amd-button">Invia richiesta di preventivo</button><p class="amd-booking-help">Conserva il collegamento al riepilogo che riceverai nella prossima pagina.</p></form></div>
@endsection
