<x-app-layout>
    @php
        $formValue = function ($name, $default = '') {
            $value = old($name, $default);
            return is_scalar($value) ? (string) $value : '';
        };
    @endphp
    <x-slot name="header"><div class="flex flex-wrap justify-between items-center gap-3"><h2 class="font-semibold text-xl text-white">Catalogo pubblico</h2><a href="{{ route('public-cars.preview.index') }}" class="rounded bg-white px-3 py-2 text-gray-900">Apri ricerca auto</a></div></x-slot>
    <div class="max-w-7xl mx-auto space-y-6">
        @if(session('status'))<div class="rounded border border-green-300 bg-green-50 text-green-900 p-4" role="status">{{ session('status') }}</div>@endif
        <div class="app-surface rounded border p-4 sm:p-6">
            <h1 class="font-semibold text-lg">{{ $editing ? 'Modifica offerta' : 'Aggiungi un’offerta al catalogo' }}</h1>
            <p class="app-muted mt-2">Scegli un listino e una sede della stessa organizzazione. La ricerca verifica noleggi, blocchi, manutenzioni e assegnazione per tutto il periodo richiesto.</p>
            <p class="mt-2"><a href="{{ route('public-cars.preview.index') }}" class="underline text-indigo-700 dark:text-indigo-300">Visualizza la ricerca con le offerte configurate, comprese le bozze</a></p>
            @if($errors->any())<div role="alert" class="text-red-700 dark:text-red-400 mt-4"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <form class="mt-5 space-y-4" method="post" action="{{ $editing ? route('public-offers.update', $editing) : route('public-offers.store') }}" x-data="{ deposit: @js($formValue('deposit_euros', $editing?->pricelist ? number_format(($editing->pricelist->deposit_cents ?? 0) / 100, 2, ',', '') : '')) }">
                @csrf @if($editing) @method('PUT') @endif
                <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
                    <div><label for="offer-pricelist" class="block text-sm font-medium mb-1">Veicolo, organizzazione e listino</label><select id="offer-pricelist" name="pricelist_id" required class="app-field w-full rounded" x-on:change="deposit = $event.target.selectedOptions[0].dataset.deposit ?? ''"><option value="">Seleziona un listino attivo</option>@foreach($pricelists as $pricelist)<option value="{{ $pricelist->id }}" data-deposit="{{ number_format(($pricelist->deposit_cents ?? 0) / 100, 2, ',', '') }}" @selected($formValue('pricelist_id', $editing?->pricelist_id) === (string)$pricelist->id)>{{ $pricelist->vehicle->plate }} — {{ $pricelist->vehicle->make }} {{ $pricelist->vehicle->model }} — {{ $pricelist->renter->name }} — {{ $pricelist->name }} (v{{ $pricelist->version }})</option>@endforeach</select></div>
                    <div><label for="offer-location" class="block text-sm font-medium mb-1">Sede di ritiro e riconsegna</label><select id="offer-location" name="location_id" required class="app-field w-full rounded"><option value="">Seleziona una sede dell’organizzazione</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected($formValue('location_id', $editing?->location_id) === (string)$location->id)>{{ $location->city }} — {{ $location->name }} — {{ $location->organization->name }}</option>@endforeach</select></div>
                </div>
                <div class="max-w-xl"><label for="offer-deposit" class="block text-sm font-medium mb-1">Cauzione (€)</label><input id="offer-deposit" name="deposit_euros" type="text" inputmode="decimal" pattern="[0-9]{1,8}([.,][0-9]{1,2})?" maxlength="11" required x-model="deposit" value="{{ $formValue('deposit_euros', $editing?->pricelist ? number_format(($editing->pricelist->deposit_cents ?? 0) / 100, 2, ',', '') : '') }}" class="app-field w-full rounded" aria-describedby="offer-deposit-help"><p id="offer-deposit-help" class="text-sm app-muted mt-1">Inserisci 0 per nessuna cauzione. L’importo viene salvato nel listino collegato e vale per i nuovi preventivi e le nuove prenotazioni. Le prenotazioni già confermate mantengono la cauzione concordata.</p></div>
                <div><label for="offer-description" class="block text-sm font-medium mb-1">Informazioni pubbliche sull’offerta</label><textarea id="offer-description" name="description" maxlength="2000" rows="3" class="app-field w-full rounded" aria-describedby="description-help">{{ $formValue('description', $editing?->description) }}</textarea><p id="description-help" class="text-sm app-muted mt-1">Scrivi soltanto condizioni che possono essere mostrate ai visitatori.</p></div>
                <input type="hidden" name="prices_include_vat" value="0">
                <label class="flex items-start gap-3"><input type="checkbox" name="prices_include_vat" value="1" class="mt-1 rounded" @checked($formValue('prices_include_vat', $editing?->prices_include_vat) === '1')><span>Confermo che il listino contiene prezzi finali al pubblico, IVA compresa.<span class="block text-sm app-muted">Vale anche per stagioni, fasce di durata e chilometri extra. Il catalogo non aggiunge automaticamente imposte.</span></span></label>
                <input type="hidden" name="is_published" value="0">
                <label class="flex items-start gap-3"><input type="checkbox" name="is_published" value="1" class="mt-1 rounded" @checked($formValue('is_published', $editing?->is_published) === '1')><span>Pubblica l’offerta nella ricerca aperta a tutti.</span></label>
                <div class="flex flex-wrap items-center gap-3"><button type="submit" class="rounded bg-indigo-700 px-4 py-2 text-white">Salva offerta</button>@if($editing)<a href="{{ route('public-offers.index') }}" class="underline">Annulla modifica</a>@endif</div>
            </form>
        </div>
        <section class="app-surface rounded border p-4 sm:p-6" id="offerte-configurate"><h2 class="font-semibold text-lg mb-4">Offerte configurate</h2>
            <form method="get" action="{{ route('public-offers.index') }}#offerte-configurate" class="mb-5 grid grid-cols-1 md:grid-cols-2 gap-4">
                <div><label for="offer-search" class="block text-sm font-medium mb-1">Cerca veicolo o organizzazione</label><input class="app-field rounded w-full" id="offer-search" name="q" type="search" maxlength="100" value="{{ $filters['q'] ?? '' }}" placeholder="Targa, marca, modello o organizzazione"></div>
                <div><label for="offer-organization" class="block text-sm font-medium mb-1">Noleggiatore operativo</label><select class="app-field rounded w-full" id="offer-organization" name="organization_id"><option value="">Tutte le organizzazioni accessibili</option>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected((string)($filters['organization_id'] ?? '') === (string)$organization->id)>{{ $organization->name }}</option>@endforeach</select></div>
                <div class="flex items-center gap-4"><button class="rounded bg-indigo-700 px-4 py-2 text-white" type="submit">Cerca offerte</button><a class="underline" href="{{ route('public-offers.index') }}#offerte-configurate">Azzera filtri</a></div>
            </form>
            <p class="text-sm app-muted mb-4">La tariffa base è giornaliera. Il totale dipende dal periodo e dalle regole del listino; la cauzione è separata.</p>
            <div class="overflow-x-auto"><table class="w-full text-sm text-left"><thead class="app-surface-subtle"><tr><th class="p-3">Veicolo</th><th class="p-3">Organizzazione e sede</th><th class="p-3">Listino</th><th class="p-3">Tariffa base / giorno</th><th class="p-3">Cauzione</th><th class="p-3">Pubblicazione</th><th class="p-3">Azioni</th></tr></thead><tbody>
                @forelse($offers as $offer)<tr class="border-t"><td class="p-3">{{ $offer->vehicle?->plate ?? 'Veicolo archiviato' }}<br>{{ $offer->vehicle?->make }} {{ $offer->vehicle?->model }}</td><td class="p-3">{{ $offer->organization?->name ?? 'Organizzazione archiviata' }}<br>{{ $offer->location?->name }}</td><td class="p-3">{{ $offer->pricelist?->name }}<br>{{ $offer->pricelist?->status_label }}</td><td class="p-3">@if($offer->pricelist)<strong class="whitespace-nowrap">{{ number_format($offer->pricelist->base_daily_cents / 100, 2, ',', '.') }} {{ $offer->pricelist->currency === 'EUR' ? '€' : $offer->pricelist->currency }}</strong><br><span class="app-muted">{{ $offer->prices_include_vat ? 'IVA inclusa' : 'IVA da verificare' }}</span>@else Non disponibile @endif</td><td class="p-3 whitespace-nowrap">{{ $offer->pricelist ? number_format($offer->pricelist->deposit_cents / 100, 2, ',', '.').' '.($offer->pricelist->currency === 'EUR' ? '€' : $offer->pricelist->currency) : 'Non disponibile' }}</td><td class="p-3">{{ $offer->is_published ? 'Pubblicata' : 'Bozza' }}@unless($offer->prices_include_vat)<br><span class="app-muted">Prezzi da verificare</span>@endunless</td><td class="p-3"><a class="underline" href="{{ route('public-offers.index', ['edit' => $offer->id] + $filters) }}">Modifica</a></td></tr>
                @empty<tr><td colspan="7" class="p-4 app-muted">{{ !empty($filters['q']) || !empty($filters['organization_id']) ? 'Nessuna offerta corrisponde ai filtri selezionati.' : 'Nessuna offerta configurata. Aggiungi un’offerta al catalogo.' }}</td></tr>@endforelse
            </tbody></table></div><div class="mt-4">{{ $offers->links() }}</div>
        </section>
    </div>
</x-app-layout>
