<x-app-layout><x-slot name="header"><h1 class="text-xl font-semibold text-white">{{ $case->reference }} · {{ $case->type === 'delivery' ? 'Consegna personalizzata' : 'Lungo termine' }}</h1></x-slot>
@php $money = fn ($cents) => $cents === null ? 'Da definire' : number_format($cents / 100, 2, ',', '.').' €'; $editable = !in_array($case->status, ['signed', 'converted']); @endphp
<div class="amr"><x-amd-rent-nav :type="$case->type" /><div class="amr-actions"><a class="amr-link" href="{{ route('amd-rent.enquiries.index', ['type' => $case->type]) }}">Torna all’elenco</a><a class="amr-link" href="{{ $case->publicUrl() }}" target="_blank" rel="noopener noreferrer">Apri riepilogo cliente</a></div>@include('amd-rent.feedback')
<header class="amr-panel app-surface"><div class="amr-row-title"><h2>{{ $case->customer_name }}</h2><strong>{{ $case->status_label }}</strong></div><p>{{ $case->email }} · {{ $case->phone }}</p>@if($case->company_name)<p>Azienda: {{ $case->company_name }}</p>@endif<p>Gestita da {{ $case->organization?->name ?? 'AMD Rent: in attesa di assegnazione' }}</p><p>{{ $case->vehicle_request }}@if($case->type === 'long_term') · {{ $case->duration_months }} mesi · {{ number_format($case->annual_km, 0, ',', '.') }} km/anno @endif</p>@if($case->notes)<p class="amr-preline">{{ $case->notes }}</p>@endif
@if($case->type === 'delivery')<h3>Indirizzo richiesto</h3><p>{{ $case->delivery_address }}</p><p>Consegna: {{ \Carbon\Carbon::parse($case->booking_context['period']['pickup_at'])->format('d/m/Y H:i') }}. Riconsegna: {{ \Carbon\Carbon::parse($case->booking_context['period']['return_at'])->format('d/m/Y H:i') }} presso {{ $case->booking_context['car']['location'] }}.</p><p>Supplemento proposto: <strong>{{ $money($case->delivery_fee_cents) }}</strong>. La richiesta non impegna l’auto: disponibilità e prezzo del noleggio saranno ricontrollati prima del pagamento.</p>@endif
@if($case->booking)<p><a class="amr-button" href="{{ route('public-bookings.index', ['q' => $case->booking->reference]) }}">Apri prenotazione {{ $case->booking->reference }}</a></p>@endif</header>
@if(app(\App\Services\AmdRent\DeliveryBookingRecovery::class)->canReopen($case))
@can('rentals.create')
<section class="amr-panel app-surface">
    <h2>Recupera la richiesta di consegna</h2>
    <p>La prenotazione {{ $case->booking->reference }} ha un pagamento non avviato o scaduto. Riapri la richiesta per consentire una nuova verifica: proposta e scadenza restano invariate, la prenotazione precedente rimane nello storico.</p>
    <form method="post" action="{{ route('amd-rent.enquiries.reopen', $case) }}">
        @csrf
        <input type="hidden" name="booking_id" value="{{ $case->public_booking_id }}">
        <input type="hidden" name="revision" value="{{ $case->revision }}">
        <button type="submit" class="amr-button">Riapri richiesta</button>
    </form>
</section>
@endcan
@endif
<div class="amr-columns amr-case-columns"><div class="amr-stack">
@if($case->type === 'long_term')
<section id="preventivi" class="amr-panel app-surface"><h2>Preventivi delle società</h2>@forelse($case->quotes as $quote)<article class="amr-quote"><div class="amr-row-title"><h3>{{ $quote->supplier }}</h3><strong>{{ $money($quote->monthly_cents) }}/mese</strong></div><p>{{ $quote->vehicle }} · {{ $quote->months }} mesi · {{ number_format($quote->annual_km, 0, ',', '.') }} km/anno</p><p>Anticipo: {{ $money($quote->upfront_cents) }} · {{ $quote->vat === 'included' ? 'IVA inclusa' : 'IVA esclusa' }} · Valido fino al {{ $quote->valid_until->format('d/m/Y') }}</p><p class="amr-preline">{{ $quote->conditions }}</p>@if((int) $case->selected_quote_id === $quote->id)<p><strong>Preventivo scelto per la pratica.</strong></p>@endif</article>@empty<p>Non sono ancora presenti preventivi.</p>@endforelse
@if(in_array($case->status, ['new', 'working', 'quoted']))@can('rentals.create')<details class="amr-disclosure"><summary>Aggiungi un preventivo</summary><form class="amr-form" method="post" action="{{ route('amd-rent.enquiries.quote', $case) }}">@csrf
<div class="amr-grid">@foreach(['supplier' => 'Società fornitrice', 'vehicle' => 'Auto proposta'] as $field => $label)<div><label for="quote-{{ $field }}">{{ $label }}</label><input class="app-field" id="quote-{{ $field }}" name="{{ $field }}" maxlength="191" value="{{ old($field) }}" required></div>@endforeach
@foreach(['months' => ['Durata (mesi)', 12, 120, 1], 'annual_km' => ['Chilometri annui', 1000, 200000, 1], 'monthly' => ['Canone mensile (€)', 0.01, 100000, 0.01], 'upfront' => ['Anticipo (€)', 0, 1000000, 0.01]] as $field => [$label, $min, $max, $step])<div><label for="quote-{{ $field }}">{{ $label }}</label><input class="app-field" id="quote-{{ $field }}" name="{{ $field }}" type="number" min="{{ $min }}" max="{{ $max }}" step="{{ $step }}" value="{{ old($field) }}" required></div>@endforeach
<div><label for="quote-vat">Trattamento IVA degli importi</label><select class="app-field" id="quote-vat" name="vat" required><option value="">Seleziona</option><option value="included">IVA inclusa</option><option value="excluded">IVA esclusa</option></select></div><div><label for="quote-valid">Valido fino al</label><input class="app-field" id="quote-valid" name="valid_until" type="date" min="{{ now()->toDateString() }}" value="{{ old('valid_until') }}" required></div></div>
<label for="quote-conditions">Servizi inclusi, esclusioni e condizioni del preventivo</label><textarea class="app-field" id="quote-conditions" name="conditions" rows="4" maxlength="5000" required>{{ old('conditions') }}</textarea><button class="amr-button">Salva preventivo</button></form></details>@endcan @endif</section>
<section id="documenti" class="amr-panel app-surface"><h2>Documenti della pratica</h2><p>I documenti restano riservati all’admin e al noleggiatore assegnato, salvo condivisione esplicita nell’area cliente. Il cliente deve accedere e verificare la propria email.</p>
@forelse($case->documents as $document)
<div class="amr-quote"><a class="amr-row" href="{{ route('amd-rent.enquiries.download', [$case, $document]) }}"><strong>{{ $document->name }}</strong><small>{{ ['customer' => 'Cliente', 'company' => 'Azienda', 'quote' => 'Preventivo', 'contract' => 'Contratto firmato'][$document->kind] }} · {{ $document->created_at->format('d/m/Y H:i') }}</small></a><p>{{ $document->customer_visible ? 'Visibile nell’area cliente.' : 'Riservato al gestionale.' }}@if($document->public_customer_id) Caricato dal cliente.@endif</p>
@can('rentals.create')<form method="post" action="{{ route('amd-rent.enquiries.document-visibility', [$case, $document]) }}">@csrf @method('PUT')<input type="hidden" name="customer_visible" value="{{ $document->customer_visible ? 0 : 1 }}"><button class="amr-button amr-button-secondary">{{ $document->customer_visible ? 'Nascondi al cliente' : 'Condividi con il cliente' }}</button></form>@endcan</div>
@empty<p>Nessun documento allegato.</p>@endforelse
@can('rentals.create')<form class="amr-form" method="post" enctype="multipart/form-data" action="{{ route('amd-rent.enquiries.upload', $case) }}">@csrf<label for="document-kind">Tipo di documento</label><select class="app-field" id="document-kind" name="kind"><option value="customer">Documenti cliente</option><option value="company">Pratica aziendale</option><option value="quote">Preventivo originale</option><option value="contract">Contratto firmato in presenza</option></select><label for="case-document">Allega PDF, JPG o PNG (massimo 10 MB)</label><input class="app-field" id="case-document" type="file" name="document" accept="application/pdf,image/jpeg,image/png" required><label class="amr-check"><input type="checkbox" name="customer_visible" value="1"><span>Condividi questo documento nell’area cliente.</span></label><button class="amr-button">Carica documento</button></form>@endcan</section>
@endif
<section class="amr-panel app-surface"><h2>Storico attività</h2>@forelse($case->events->sortByDesc('id') as $event)<p><small>{{ $event->created_at->format('d/m/Y H:i') }}</small><br>{{ $event->description }}</p>@empty<p>Richiesta ricevuta il {{ $case->created_at->format('d/m/Y H:i') }}.</p>@endforelse</section>
</div><aside class="amr-stack">
@if($editable)@can('rentals.create')<form class="amr-panel app-surface amr-form" method="post" action="{{ route('amd-rent.enquiries.update', $case) }}">@csrf @method('PUT')<input type="hidden" name="revision" value="{{ $case->revision }}"><h2>Gestisci la pratica</h2>
@if(auth()->user()->hasRole('admin') && $case->type === 'long_term')<label for="case-organization">Noleggiatore assegnato</label><select class="app-field" id="case-organization" name="organization_id"><option value="">Da assegnare</option>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected((int) $case->organization_id === $organization->id)>{{ $organization->name }}</option>@endforeach</select>@endif
<label for="case-state">Stato della pratica</label><select class="app-field" id="case-state" name="status">@foreach(\App\Models\AmdRentEnquiry::STATUSES as $key => $label)@if($key !== 'converted' && ($case->type === 'long_term' || !in_array($key, ['accepted','signed'])))<option value="{{ $key }}" @selected($case->status === $key)>{{ $label }}</option>@endif @endforeach</select>
@if($case->type === 'delivery')<p>Pubblicando il preventivo confermi di poter consegnare all’indirizzo richiesto. Il supplemento riguarda la consegna; la riconsegna resta presso il luogo scelto nella ricerca.</p><label for="delivery-fee">Supplemento finale, IVA inclusa (€)</label><input class="app-field" id="delivery-fee" name="delivery_fee" type="number" min="0" max="100000" step="0.01" value="{{ old('delivery_fee', $case->delivery_fee_cents === null ? '' : $case->delivery_fee_cents / 100) }}"><label for="delivery-expiry">Proposta valida fino al</label><input class="app-field" id="delivery-expiry" type="date" name="quote_valid_until" min="{{ now()->toDateString() }}" value="{{ old('quote_valid_until', $case->quote_expires_at?->toDateString()) }}">
@else
<label for="selected-quote">Preventivo scelto dal cliente</label><select class="app-field" id="selected-quote" name="selected_quote_id"><option value="">Non ancora scelto</option>@foreach($case->quotes as $quote)<option value="{{ $quote->id }}" @selected((int) $case->selected_quote_id === $quote->id)>{{ $quote->supplier }} · {{ $quote->vehicle }} · {{ $money($quote->monthly_cents) }}/mese</option>@endforeach</select>
<details class="amr-disclosure"><summary>Conclusione del contratto in presenza</summary><p>Accetta prima il preventivo scelto, allega il contratto firmato e poi seleziona “Contratto concluso in presenza”.</p><label for="contract-reference">Riferimento contratto</label><input class="app-field" id="contract-reference" name="contract_reference" maxlength="191" value="{{ old('contract_reference', $case->contract_reference) }}"><label for="signed-date">Data della firma</label><input class="app-field" id="signed-date" name="signed_at" type="date" max="{{ now()->toDateString() }}" value="{{ old('signed_at', $case->signed_at?->toDateString()) }}"><label class="amr-check"><input type="checkbox" name="signed_in_person" value="1"><span>Confermo che il contratto è stato concluso di persona.</span></label></details>
@endif<button class="amr-button">Salva aggiornamento</button></form>@endcan @endif
@if($case->type === 'long_term')
<section class="amr-panel app-surface"><h2>Commissioni della pratica</h2><p>Quota noleggiatore: <strong>{{ $money($case->renter_commission_cents) }}</strong></p><p>Stato: {{ ['expected' => 'Prevista', 'earned' => 'Maturata', 'paid' => 'Liquidata'][$case->commission_status] }}</p>
@if(auth()->user()->hasRole('admin'))<form class="amr-form" action="{{ route('amd-rent.enquiries.commissions', $case) }}" method="post">@csrf @method('PUT')<input type="hidden" name="revision" value="{{ $case->revision }}"><label for="platform-commission">Commissione AMD Rent (€)</label><input class="app-field" id="platform-commission" name="platform_commission" type="number" min="0" max="1000000" step="0.01" value="{{ $case->platform_commission_cents === null ? '' : $case->platform_commission_cents / 100 }}"><label for="renter-commission">Commissione noleggiatore (€)</label><input class="app-field" id="renter-commission" name="renter_commission" type="number" min="0" max="1000000" step="0.01" value="{{ $case->renter_commission_cents === null ? '' : $case->renter_commission_cents / 100 }}"><label for="commission-state">Stato commissioni</label><select class="app-field" id="commission-state" name="commission_status">@foreach(['expected' => 'Prevista', 'earned' => 'Maturata', 'paid' => 'Liquidata'] as $key => $label)<option value="{{ $key }}" @selected($case->commission_status === $key)>{{ $label }}</option>@endforeach</select><button class="amr-button">Aggiorna commissioni</button></form>@endif</section>
@endif
</aside></div></div></x-app-layout>
