<?php

// Explicitly verified model images. Never match a different model by a loose substring.
return [
    'fiat-panda' => [
        'makes' => ['Fiat'],
        'models' => ['Panda'],
        'file' => 'fiat-panda.jpg',
        'mime_type' => 'image/jpeg',
        'source_name' => 'AMD Mobility',
        'source_url' => 'https://amdmobility.it/auto-economy/',
        'original_url' => 'https://amdmobility.it/wp-content/uploads/2025/01/Panda_Hero-removebg-preview.jpg',
    ],
    'fiat-600' => [
        'makes' => ['Fiat'],
        'models' => ['600 1.2 HYBRID 145CV'],
        'file' => 'fiat-600.jpg',
        'mime_type' => 'image/jpeg',
        'source_name' => 'AMD Mobility',
        'source_url' => 'https://amdmobility.it/auto-economy/',
        'original_url' => 'https://amdmobility.it/wp-content/uploads/2025/01/fiat_600_top_ant-removebg-preview-1.jpg',
    ],
    'lancia-ypsilon' => [
        'makes' => ['Lancia'],
        'models' => ['YPSILON 100CV'],
        'file' => 'lancia-ypsilon.jpg',
        'mime_type' => 'image/jpeg',
        'source_name' => 'AMD Mobility',
        'source_url' => 'https://amdmobility.it/auto-economy/',
        'original_url' => 'https://amdmobility.it/wp-content/uploads/2026/05/Y.jpg',
    ],
    'seat-arona' => [
        'makes' => ['Seat'],
        'models' => ['Arona', 'ARONA 1.0 BLACK EDITION'],
        'file' => 'seat-arona.jpg',
        'mime_type' => 'image/jpeg',
        'source_name' => 'AMD Mobility',
        'source_url' => 'https://amdmobility.it/auto-economy/',
        'original_url' => 'https://amdmobility.it/wp-content/uploads/2025/01/seat_arona_ant_0-removebg-preview-1-1.jpg',
    ],
    'alfa-romeo-tonale' => [
        'makes' => ['Alfa Romeo'],
        'models' => ['Tonale'],
        'file' => 'alfa-romeo-tonale.png',
        'mime_type' => 'image/png',
        'source_name' => 'Alfa Romeo',
        'source_url' => 'https://www.alfaromeo.it/modelli/tonale',
        'original_url' => 'https://www.alfaromeo.it/content/dam/alfa/cross/tonale-mp/new-version-2025/figurines/AR-Tonale_MHEV-MCA_Base_Ibrida.png',
    ],
    'alfa-romeo-junior' => [
        'makes' => ['A.R.', 'Alfa Romeo'],
        'models' => ['JUNIOR'],
        'file' => 'alfa-romeo-junior.jpg',
        'mime_type' => 'image/jpeg',
        'source_name' => 'AMD Mobility',
        'source_url' => 'https://amdmobility.it/auto-economy/',
        'original_url' => 'https://amdmobility.it/wp-content/uploads/2026/05/junior.jpg',
    ],
    'jaecoo-5' => [
        'makes' => ['Jaecoo'],
        'models' => ['Jaecoo 5'],
        'file' => 'jaecoo-5.png',
        'mime_type' => 'image/png',
        'source_name' => 'Omoda & Jaecoo Italia',
        'source_url' => 'https://www.omodajaecooitalia.com/modelli/jaecoo-5/',
        'original_url' => 'https://omodajaecooitalia.com/wp-content/uploads/j5.png',
    ],
    'toyota-aygo-x' => [
        'makes' => ['Toyota'],
        'models' => ['Aygo X'],
        'file' => 'toyota-aygo-x.png',
        'mime_type' => 'image/png',
        'source_name' => 'Toyota',
        'source_url' => 'https://www.toyota.it/gamma/aygo-x',
        'original_url' => 'https://img-optimize.toyota-europe.com/ccis/zip/it/product-token/c9f9e3a1-1d29-4c09-b504-6a488e2755d3/vehicle/93637/width/680/height/383/padding/0,0,0,0/image-quality/70/day-exterior-03_M50.png',
    ],
    'toyota-yaris' => [
        'makes' => ['Toyota'],
        'models' => ['Yaris'],
        'file' => 'toyota-yaris.png',
        'mime_type' => 'image/png',
        'source_name' => 'Toyota',
        'source_url' => 'https://www.toyota.it/gamma/aygo-x',
        'original_url' => 'https://img-optimize.toyota-europe.com/ccis/zip/it/product-token/5e0f42fd-6dd4-4104-b2b1-86add1e6cbbb/vehicle/97726/width/680/height/383/padding/0,0,0,0/image-quality/70/day-exterior-03_1K3.png',
    ],
    'toyota-proace-verso' => [
        'makes' => ['Toyota'],
        'models' => ['Proace 9 Posti'],
        'file' => 'toyota-proace-verso.png',
        'mime_type' => 'image/png',
        'source_name' => 'Toyota',
        'source_url' => 'https://www.toyota.it/gamma/aygo-x',
        'original_url' => 'https://img-optimize.toyota-europe.com/ccis/zip/it/product-token/2424e2c0-3eba-443e-93d0-8199f77d5839/vehicle/95895/width/680/height/383/padding/0,0,0,0/image-quality/70/day-exterior-03_EPR.png',
    ],
    'fiat-500' => [
        'makes' => ['Fiat'],
        'models' => ['500'],
        'file' => 'fiat-500.jpg',
        'mime_type' => 'image/jpeg',
        'source_name' => 'Fiat',
        'source_url' => 'https://www.fiat.it/modello/nuova-fiat-500-ibrida?modelCode=3900',
        'original_url' => 'https://www.fiat.it/content/dam/fiat2023/cross/model-range/new-500-hybrid/mobile.jpg',
    ],
    'citroen-c3' => [
        'makes' => ['Citroen', 'Citroën'],
        'models' => ['C3'],
        'file' => 'citroen-c3.png',
        'mime_type' => 'image/png',
        'source_name' => 'Citroën',
        'source_url' => 'https://www.citroen.it/modelli/c3.html',
        'original_url' => 'https://www.citroen.it/content/dam/citroen/master/b2c/models/c3-2026/trims-cards/C3_You_trim-card.png?imwidth=768',
    ],
    'peugeot-208' => [
        'makes' => ['Peugeot'],
        'models' => ['208', '208 1.2 hybrid Allure 100cv'],
        'file' => 'peugeot-208.png',
        'mime_type' => 'image/png',
        'source_name' => 'Peugeot',
        'source_url' => 'https://www.peugeot.it/gamma-modelli/nuova-peugeot-208/208-ibrido-benzina.html',
        'original_url' => 'https://www.peugeot.it/content/dam/peugeot/master/b2c/our-range/showroom/208/immersive-update/208-hybrid-petrol/TRIM_208_HYBRID_ALLURE.png',
    ],
    'nissan-primastar' => [
        'makes' => ['Nissan'],
        'models' => ['Prima Star'],
        'file' => 'nissan-primastar.png',
        'mime_type' => 'image/png',
        'source_name' => 'Nissan',
        'source_url' => 'https://www.nissan.it/veicoli/veicoli-nuovi/primastar-bus.html',
        'original_url' => 'https://www-europe.nissan-cdn.net/content/dam/Nissan/it/vehicles/Primastar_Combi_X82/VAP/Packshot/Primastar_Combi_VAP_2023_600x320.png.ximg.l_3_m.smart.png',
    ],
    'jeep-renegade' => [
        'makes' => ['Jeep'],
        'models' => ['Renegade'],
        'file' => 'jeep-renegade.jpg',
        'mime_type' => 'image/jpeg',
        'source_name' => 'Charles / Wikimedia Commons (CC0)',
        'source_url' => 'https://commons.wikimedia.org/wiki/File:Jeep_Renegade_1.3_T-GDI_(2021)_(54730275753).jpg',
        'original_url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Jeep_Renegade_1.3_T-GDI_%282021%29_%2854730275753%29.jpg/960px-Jeep_Renegade_1.3_T-GDI_%282021%29_%2854730275753%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail',
        'license' => 'CC0 1.0',
    ],
    'jeep-avenger' => [
        'makes' => ['Jeep'],
        'models' => ['Avenger'],
        'file' => 'jeep-avenger.png',
        'mime_type' => 'image/png',
        'source_name' => 'Jeep',
        'source_url' => 'https://www.jeep-official.it/jeep-avenger/elettrica',
        'original_url' => 'https://www.jeep-official.it/content/dam/jeep/crossmarket/avenger-mca/bev/04-trim/longitude/JEEP-AVENGER-MCA-LONGITUDE-4X2-RANGE-MY26-565x330-FIGURINE.png',
    ],
];
